#!/bin/sh

# Generates wrapper.h
# Usage:
#   generate_wrapper <git-tag to checkout pd at>

tag=$1

root=$(pwd)/$(dirname "$0")
root=$(echo "$root" | sed "s/\/\.//")
libpd_src="$root/libpd"

update_libpd() {
    rm -rf "$libpd_src"
    git clone https://github.com/libpd/libpd.git "$libpd_src"
    cd "$libpd_src" || exit
    git checkout tags/"${tag}"
    git submodule update --init
    cd .. || exit
}

rm_unused() {
    cd "$libpd_src" || exit

    # keep only pd sources and libpd stuff
    items=$(ls -a)
    for item in $items; do
        if [ "$item" != "." ] && [ "$item" != ".." ] && 
            [ "$item" != "libpd_wrapper" ] && [ "$item" != "pure-data" ] &&
            [ "$item" != "CHANGES.txt" ] && [ "$item" != "LICENSE.txt" ] &&
            [ "$item" != "README.md" ]; then
            rm -rf "$item"
        fi
    done

    unused_pd_stuff="pure-data/.git \
                pure-data/.gitattributes \
                pure-data/.gitignore \
                pure-data/.travis.yml \
                pure-data/INSTALL.htm \
                pure-data/Makefile.am \
                pure-data/asio \
                pure-data/autogen.sh \
                pure-data/configure.ac \
                pure-data/doc \
                pure-data/font \
                pure-data/linux  \
                pure-data/m4 \
                pure-data/mac  \
                pure-data/man \
                pure-data/md \
                pure-data/msw  \
                pure-data/pd.pc.in \
                pure-data/po \
                pure-data/portaudio \
                pure-data/portmidi  \
                pure-data/src/d_fft_fftw.c \
                pure-data/src/s_audio_alsa.c \
                pure-data/src/s_audio_alsa.h \
                pure-data/src/s_audio_alsamm.c \
                pure-data/src/s_audio_audiounit.c \
                pure-data/src/s_audio_esd.c \
                pure-data/src/s_audio_jack.c \
                pure-data/src/s_audio_mmio.c \
                pure-data/src/s_audio_oss.c \
                pure-data/src/s_audio_pa.c \
                pure-data/src/s_audio_paring.c \
                pure-data/src/s_audio_paring.h \
                pure-data/src/s_entry.c \
                pure-data/src/s_midi.c \
                pure-data/src/s_midi_alsa.c \
                pure-data/src/s_midi_dummy.c \
                pure-data/src/s_midi_mmio.c \
                pure-data/src/s_midi_oss.c \
                pure-data/src/s_midi_pm.c \
                pure-data/src/s_watchdog.c \
                pure-data/src/u_pdreceive.c \
                pure-data/src/u_pdsend.c \
                pure-data/tcl"

    for item in $unused_pd_stuff; do
        rm -rf "$item"
    done

    cd - || exit
}

generate_wrapper() {
    wrapper="$root/wrapper.h"
    rm -f "$wrapper"
    touch "$wrapper"

    cd "$libpd_src/libpd_wrapper" || exit

    # z_libpd.h should be first
    {
    echo "// this file is automatically generated by command:"
    echo "// ./generate_wrapper.sh ${tag}"
    echo "#include \"z_libpd.h\""
    } >> "$wrapper"

    # exclude z_libpd.h from the loop
    mv z_libpd.h ../

    for h in *.h; do
        echo "#include \"${h}\"" >> "$wrapper"
    done

    # utils
    for h in util/*.h; do
        echo "#include \"${h}\"" >> "$wrapper"
    done

    # return m_pd.h back
    mv ../z_libpd.h .

    cd - || exit
}

update_libpd
rm_unused
generate_wrapper
