// this file is automatically generated by command:
// ./generate_wrapper.sh 0.12.1
#include "z_libpd.h"
#include "x_libpdreceive.h"
#include "z_hooks.h"
#include "util/ringbuffer.h"
#include "util/z_print_util.h"
#include "util/z_queued.h"
